#!/usr/bin/env bash
#Bash script that configures nginx web server

sudo apt-get update -y

sudo apt-get install ngnix -y

echo 'Hello World!' | sudo tee -a /var/www/html/index.html

service ngnix restart
