#!/usr/bin/env bash
# configures a new server

# Install nginx on the servers
apt-get -y update
apt-get -y install nginx

# Add custom response header to know the server name
HOST_NAME=$(hostname)
HEADERFILE="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
ELO=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $ELO ]]; then
    sed -i "23i $HEADERFILE" /etc/nginx/sites-available/default
fi

# Create a first index.html page
echo "Hello World!" > /var/www/html/index.html

# Add to the nginx configuration file a redirection
ELO=$(grep "redirect_me" /etc/nginx/sites-available/default)
REDIRECT="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
if [[ -z $ELO ]]; then
    sed -i "42i $REDIRECT" /etc/nginx/sites-available/default
fi

# Add to the nginx configuration file a error page 404
ELO=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERRORPAGE="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $ELO ]]; then
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sed -i "40i $ERRORPAGE" /etc/nginx/sites-available/default
fi

service nginx restart
